### ISSUE TITLE
Accept list of prompts in API

### ISSUE THREAD

**Issue by AlexKoff88** [andreyanufr/who_what_benchmark#5]
Can we change API so that it can work with list of prompts instead of JSON files:
```python
prompts = [
"What it PyTorch",
"Who is Mahatma Gandhi",
]
metrics_per_prompt, metrics = evaluator.score(optimized_model, prompts=prompts)
```

This is more flexible, IMO.

**Comment by AlexKoff88** [comment]
You will be also able to do the following thing in the script:
```python
from datasets import load_dataset
val = load_dataset("lambada", split="validation[20:40]")
prompts = val["text"]
...
metrics_per_prompt, metrics = evaluator.score(optimized_model, prompts=prompts)
```

This should help to validate Chinese models easily and it is worth stating it in the README.

**Comment by andreyanufr** [comment]
@AlexKoff88. Is this variant appropriate https://github.com/andreyanufr/who_what_benchmark/pull/7/ ?
